# Generated by Django 4.0.5 on 2023-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=300, null=True, upload_to='Equipment'),
        ),
    ]
