# Generated by Django 4.0.5 on 2023-02-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(default='', max_length=300, upload_to='Equipment'),
        ),
    ]
