# Generated by Django 4.1.4 on 2023-04-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteengineer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='No Pic', max_length=200, null=True, upload_to='Profile'),
        ),
        migrations.AddField(
            model_name='siteengineer',
            name='qualification_proof',
            field=models.FileField(blank=True, default='No File', max_length=300, null=True, upload_to='Qualification'),
        ),
        migrations.AddField(
            model_name='siteengineer',
            name='specializations_proof',
            field=models.FileField(blank=True, default='No File', max_length=300, null=True, upload_to='Specialization'),
        ),
    ]
